Target makefile now detects oofem error codes and reports test failure into test_results file.

diff --git a/base/target_makefile.in b/base/target_makefile.in
--- a/base/target_makefile.in
+++ b/base/target_makefile.in
@@ -60,7 +60,8 @@ tests:
 		      ${PYTHON} ${CHECKER} ${CHECKER_PARAMS} -f $$i    >> ${RESULT};\
 		      rm $${ib%.in}.out;\
 	      else \
-		      echo "FAILED: Error return code detected ($$?)";\
+		      echo "OOFEM: $${ib} - Error Return Code detected ($$?)" >> ${RESULT};\
+		      echo "                                                                   [FAILED]">> ${RESULT};\
 	      fi;\
 	    done;\
 	  done;\
